name: Deploy Songbook

permissions:
 id-token: write # Required for GitHub to be able to create a token for you to authenticate with AWS
 contents: read  # Permits your action to read this repo.

on:
 push:
   branches:
     - main

jobs:
  deploy_cdk:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: aws/package-lock.json

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_GITHUB_ACTIONS_ROLE }}
          aws-region: ${{ vars.AWS_TARGET_REGION }}
          role-session-name: "GitHubActions-DeployLayerStack"

      - name: Install dependencies
        working-directory: aws
        run: npm ci

      - name: CDK Diff
        working-directory: aws
        run: npm run -- cdk diff -c config=dev

      - name: CDK Deploy
        working-directory: aws
        run: npm run -- cdk deploy --all -c config=dev --require-approval never